; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;
; !!! IMPORTANT: Use the calibration values from TFT_eSPI_User_Setup.txt for the 2.8" TFT with XPT2046 touch controller 
[platformio]
src_dir = src
default_envs = esp32dev
description = TFT_eSPI Menu example for ESP32 with XPT2046 touch controller.

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM7
monitor_port = COM7
monitor_filters = esp32_exception_decoder
upload_speed = 921600
board_build.partitions = min_spiffs.csv
board_build.flash_mode = dio
board_build.f_flash = 80000000
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4
	arduino-libraries/NTPClient@^3.2.1
	bblanchon/ArduinoJson@^7.2.2
